---
# tasks file for apache
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install apache2 package
      apt:
        name: apache2
        state: present
      become: yes

    - name: Enable apache2 at startup
      systemd:
        name: apache2
        enabled: yes
      become: yes

    - name: Start apache2 service
      systemd:
        name: apache2
        state: started
      become: yes

    - name: Copy apache configuration file
      copy:
        src: ../files/apache2.conf
        dest: /etc/apache2/apache2.conf
      become: yes

    - name: Restart apache2 service
      systemd:
        name: apache2
        state: restarted
      become: yes
